### ISSUE TITLE
Aurelia Example API

### ISSUE THREAD

**Issue by dmason511** [devscott/identityServer3Example#2]
Scott,
Thank you for the Aurelia Example, really helps when you trying to come up to speed on a new framework.
I have been able to get the MVC example to work but as far as the Aurelia Example, I am unable to get the call to the API to work.
The api is running but when I click the "Github Users" button, nothing happens.
If you could point me in the right direction to solve this issue, it would be greatly appreciated.

Thanks,
DM

**Comment by devscott** [comment]
@dmason511  Without seeing any code it is kinds of hard to help as it could anything.

**Comment by dmason511** [comment]
I pulled the code straight from the Github.  I followed the instructions for running the app.  the Authentication works against the IDSrv and I am logged in.  I click the Github users button and nothing happens.

**Comment by dmason511** [comment]
Where is the bearer token added to the header for the api? I have the token but cannot find where it is added to the header.
