### ISSUE TITLE
Aurelia: 404 when authenticating with 'Login' button

### ISSUE THREAD

**Issue by jhoerr** [devscott/identityServer3Example#3]
Hi Scott, thanks so much for putting these examples together. It's really helping me make sense of Aurelia and IdentityServer 3.

Out of the box i'm getting a 404 on the request to `POST https://localhost:44301/core/auth/login` when I use the 'Login' option. Is this method supported?

I also noticed that I had to add CORS headers in the web.config for this request to be accepted by the identity server. I don't know if this is related. Here are the additions I made.

```
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Methods" value="GET,POST,PUT,DELETE,OPTIONS" />
        <add name="Access-Control-Allow-Headers" value="Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
```

And here is a screengrab of the 404 in Chrome after clicking the Login button:

![image](https://cloud.githubusercontent.com/assets/1151206/17780736/6dcb24ca-653a-11e6-88fb-6ae90f5110c0.png)

**Comment by jhoerr** [comment]
After poking around more it appears that adding those CORS headers results in another CORS issue when  the Aurelia app tries to `GET /core/connect/userinfo` from IdentityServer3. Removing the headers from the web.config allows the `/userinfo` request to complete successfully.

**Comment by devscott** [comment]
@jhoerr yeah you shouldn't have to add CORS to anything.

**Comment by jhoerr** [comment]
Cool -- thanks for confirming that. CORS aside, do you have any thoughts on whether the standard username/password login should work out of the box?

**Comment by devscott** [comment]
@jhoerr yes it should. Although I must admit, it has been awhile since I last work on this project. If something changed upstream and/or you are pulling down newer npm packages, it may not.

**Comment by jhoerr** [comment]
Ok, thanks! And thanks again for putting all this together.
